apiVersion: v1
kind: Secret
metadata:
  name: fcg-secrets
  namespace: fcg
type: Opaque
stringData:
  RabbitMq__Username: fcg
  RabbitMq__Password: fcg_dev_password
  Jwt__Key: 3wHWWGbqCLKsNmRjyXF2l2Y025Dp9E4fZ0llJSZpkxwa7NsEl4lXTkHSe/aMCraQQaTzLxm9gczG6CFAuX2mww==
  Seed__AdminPassword: Admin@123
  POSTGRES_USER: fcg
  POSTGRES_PASSWORD: fcg_dev_password
  UsersDatabase: Host=postgres;Port=5432;Database=fcg_users;Username=fcg;Password=fcg_dev_password
  CatalogDatabase: Host=postgres;Port=5432;Database=fcg_catalog;Username=fcg;Password=fcg_dev_password
  PaymentsDatabase: Host=postgres;Port=5432;Database=fcg_payments;Username=fcg;Password=fcg_dev_password
  NotificationsDatabase: Host=postgres;Port=5432;Database=fcg_notifications;Username=fcg;Password=fcg_dev_password
