apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  namespace: fcg
type: Opaque
stringData:
  RabbitMq__Username: fcg
  RabbitMq__Password: replace-before-production
  Jwt__Key: replace-with-a-secure-key-at-least-32-characters
  Seed__AdminPassword: replace-before-production
